// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0yhQhfS6Mb2kdHxxHxcZ-ErgY0UtSx2A',
    appId: '1:527069420412:web:aa67c297eb1ed98cd722f9',
    messagingSenderId: '527069420412',
    projectId: 'ucolorpi-app',
    authDomain: 'ucolorpi-app.firebaseapp.com',
    storageBucket: 'ucolorpi-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABhgbz87LARsvUztsuyOzMAqnFaCRsBOU',
    appId: '1:527069420412:android:22bb481c185e9f36d722f9',
    messagingSenderId: '527069420412',
    projectId: 'ucolorpi-app',
    storageBucket: 'ucolorpi-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ_xNW0kZ0Y1uZztdlOrzcopDqM0kc_1U',
    appId: '1:527069420412:ios:df9526db8c7a0c1ad722f9',
    messagingSenderId: '527069420412',
    projectId: 'ucolorpi-app',
    storageBucket: 'ucolorpi-app.firebasestorage.app',
    iosBundleId: 'com.example.ui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ_xNW0kZ0Y1uZztdlOrzcopDqM0kc_1U',
    appId: '1:527069420412:ios:df9526db8c7a0c1ad722f9',
    messagingSenderId: '527069420412',
    projectId: 'ucolorpi-app',
    storageBucket: 'ucolorpi-app.firebasestorage.app',
    iosBundleId: 'com.example.ui',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0yhQhfS6Mb2kdHxxHxcZ-ErgY0UtSx2A',
    appId: '1:527069420412:web:15573fcad7746f3bd722f9',
    messagingSenderId: '527069420412',
    projectId: 'ucolorpi-app',
    authDomain: 'ucolorpi-app.firebaseapp.com',
    storageBucket: 'ucolorpi-app.firebasestorage.app',
  );
}
